config/routes.rb
Winzo::Application.routes.draw do
  get "mocks/mock_activities", as: "mock_activities"

  get "mocks/mock_products", as: "mock_products"

  mount CommunityEngine::Engine => "/"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/mocks_controller.rb
class MocksController < BaseController
  def mock_activities
  end

  def mock_products
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mocks_helper.rb
module MocksHelper
end

app/views/admin/comments.html.haml
.yui-b.sidebar
  = render :partial => 'shared/admin_nav'

  -box do
    = form_for @search, :url => admin_comments_path, :html => {:class => "MainForm"} do |f|

      %label= :commentable_type.l
      = f.text_field :commentable_type_like

      %label= :commentable_id.l
      = f.text_field :commentable_id_equals

      %label= :email.l
      = f.text_field :author_email_or_user_email_like

      %p= f.submit :search.l




#yui-main
  .yui-b
    -box do
      %h3
        = configatron.community_name
        = :comments.l

      = paginate @comments

      = form_tag delete_selected_comments_path, :method => :delete, :id => 'comments' do
        %table{"cellspacing"=>"0", "border"=>"0", "cellpadding"=>"0", "width"=>"100%", :style => "table-layout:fixed;"}
          %thead
            %tr
              %th{:width => '30px', :colspan => '2'}
              %th=:author.l
              %th{:width => "250px"}=:body_text.l
              %th=:on_commentable.l

          %tbody
            - @comments.each do |comment|
              %tr{:id => "comment_#{comment.id}"}
                %td=link_to_remote(image_tag('icons/delete.png'), {:url => commentable_comment_path(comment.commentable_type, comment.commentable_id, comment), :method => :delete, 500 => 'alert(\'Sorry, there was a server error\'); return false',  :success => visual_effect(:fade, "comment_#{comment.id}"), :confirm => "Are you sure you want to permanently delete this comment"} )
                %td.approve
                  -if comment.pending?
                    =link_to_remote(image_tag('icons/accept.png'), {:url => approve_commentable_comment_path(comment.commentable_type, comment.commentable_id, comment, :approve => true), :method => :put, :confirm => "Approve this comment?"} )
                %td= check_box_tag "delete[]", comment.id
                %td
                  .left
                    -if comment.user
                      = link_to h(comment.user.login), user_path(comment.user)
                      %br
                      %small= comment.user.email
                    -else
                      = link_to_unless(comment.author_url.blank?, h(comment.username), h(comment.author_url)){ h(comment.username) }
                      %br
                      %small=comment.author_email
                      %br
                      %small="(#{comment.author_url})"
                %td{:style => 'overflow:hidden;'}
                  = comment.comment
                %td
                  =link_to comment.commentable_name, commentable_url(comment)
          %tfoot
            %tr
              %td{ :colspan => "4" }
                -if @comments.any?
                  %a{:href=>"#", :onclick=>"checkboxes.each(function(e){ e.checked = (e.checked == 0 ? 1 : 0) }); return false;"} Toggle all
                  %p= submit_tag :delete_selected.l

      = paginate @comments

-content_for :end_javascript do
  :javascript
    var form = $('comments');
    checkboxes = form.getInputs('checkbox');

app/views/admin/events.html.haml
.yui-b
  = render :partial => 'shared/admin_nav'

#yui-main
  .yui-b
    -box do 
      %h3=:events.l

      %table{:width=>"100%"}
        %tr 
          %th=:name.l
          %th=:metro_area.l
          %th=:when.l
          %th=:actions.l

        - for event in @events
          %tr
            %td= event.name
            %td= event.try(:metro_area).try(:name)
            %td=h event.time_and_date
            %td
              = link_to :show.l, event_path(event)
              | 
              = link_to :edit.l, edit_event_path(event)
              |
              = link_to :clone.l, clone_event_path(event)
              |
              = link_to :destroy.l, event_path(event), :confirm => :are_you_sure.l, :method => :delete

      %p= link_to :new_event.l, new_event_path

    .pagination=paginating_links @events if @events.total_count > 1

app/views/admin/messages.html.haml
.yui-b.sidebar
  = render :partial => 'shared/admin_nav'

= render :partial => "messages/sent"

app/views/admin/users.html.haml
.yui-b.sidebar
  = render :partial => 'shared/admin_nav'

#yui-main
  .yui-b
    -box do
      %h3
        = configatron.community_name
        = :members.l

      = form_tag admin_users_url, :class => 'MainForm', :method => :get do
        %label= :user_login.l
        = text_field_tag 'login', params['login']
        %label= :user_e_mail.l
        = text_field_tag 'email', params['email']
        %p
          %input{:type=>"submit", :value=> :search_users.l }

        = paginate @users

      = form_tag delete_selected_users_path, :id => 'users' do
        %table{"cellspacing"=>"0", "border"=>"0", "cellpadding"=>"0", "width"=>"100%"}
          %thead
            %tr
              %th{:width => '60px', :colspan => '3'}
              %th=:login.l
              %th=:e_mail.l
              %th=:status.l
              %th=:actions.l

          %tbody
            - @users.each do |user|
              %tr{:id => "user_#{user.id}"}
                %td
                  = link_to_remote(image_tag('icons/delete.png'), {:url => user_path(user), :method => :delete, :success => visual_effect(:fade, "user_#{user.id}"), :confirm => "Are you sure you want to permanently delete this user"} )                                                                          
                %td
                  -if !configatron.akismet_key.nil?                
                    = link_to_remote(image_tag('icons/bad-flag.png'), {:url => user_path(user, :spam => true), :method => :delete, 500 => 'alert(\'Sorry, there was a server error\'); return false',  :success => visual_effect(:fade, "user_#{user.id}"), :confirm => "Are you sure you want to permanently delete this user and mark it as spam!?"} )                                                
                %td= check_box_tag "delete[]", user.id
                
                %td
                  -if user.avatar
                    = image_tag user.avatar.photo.url(:thumb), :width => 25, :height => 25
                  = link_to h(user.login), user_path(user)
                %td
                  = h user.email
                %td
                  = user.active? ? :active.l : :inactive.l
                %td
                  = link_to( :assume_id.l , assume_user_path(user), :method => :post )
                  = " | #{link_to(:activate.l, :controller => "/admin", :action => "activate_user", :id => user.id)}".html_safe unless user.active?

          %tfoot
            %tr
              %td{ :colspan => "4" }
                -if @users.any?
                  %a{:href=>"#", :onclick=>"checkboxes.each(function(e){ e.checked = (e.checked == 0 ? 1 : 0) }); return false;"} Toggle all              
                  %p
                    -if !configatron.akismet_key.nil?
                      = check_box_tag :spam
                      =:delete_selected_mark_as_spam.l
                      %br
                    = submit_tag :delete_selected.l
  
        = paginate @users

-content_for :end_javascript do
  :javascript
    var form = $('users');
    checkboxes = form.getInputs('checkbox');        

app/views/categories/_tips.html.haml
- if category 
  %h3= category.name
  %p= category.tips
- else 
  %h3=:we_need_you.l
  %p
    %em
      =:every_person_has_something_to_say.l




app/views/categories/edit.html.haml
.yui-b.sidebar
  = render :partial => 'shared/admin_nav'

#yui-main
  -box :class => "yui-b" do
    %h3=:editing_category.l
    = form_for(:category, :url => category_path(@category), :html => { :method => :put, :class => "MainForm" }) do |f|

      %label
        =:name.l
        \:
      = f.text_field :name

      %label
        =:posting_tips.l
        \:
      = f.text_area :tips, :rows => 3

      %label
        =:new_post_text.l
        \:
      = f.text_field :new_post_text

      %label
        =:navigation_menu_text.l
        \:
      = f.text_field :nav_text

      %p
        = submit_tag :update.l

    = link_to :show.l, category_path(@category)
    |
    = link_to :back.l, categories_path

app/views/categories/index.html.haml
.yui-b
  = render :partial => 'shared/admin_nav'

#yui-main
  .yui-b
    -box do 
      %h3=:categories.l

      %table{:width=>"100%"}
        %tr 
          %th=:name.l
          %th 
            \# 
            =:posts.l
          %th=:actions.l

        - for category in @categories
          %tr
            %td= category.name
            %td= category.posts.size	
            %td
              = link_to :show.l, category_path(category)
              | 
              = link_to :edit.l, edit_category_path(category)
              |
              = link_to :destroy.l, category_path(category), :confirm => :are_you_sure.l, :method => :delete

      %br

      = link_to :new_category.l, new_category_path

app/views/categories/new.html.haml
-box do
  %h3= :new_category.l

  = form_for(:category, :url => categories_path, :html => {:class => "MainForm"}) do |f|
    %label= :name.l
    = f.text_field :name
    %p= submit_tag :create.l

  = link_to :back.l, categories_path 

app/views/categories/show.html.haml
- @meta = { :description => "#{@category.name} posts.",:keywords => "#{@category.name}"}
- @section = @category.name

.yui-b
  -box do 
    - if logged_in?
      %h3.signup=:have_something_to_contribute.l
      %ul.list.checks
        %li= link_to @category.display_new_post_text() || :write_new_post.l(:category=>@category.name), new_user_post_path({:user_id => current_user, 'post[category_id]' => @category.id})
    - else
      %h3.signup= @category.display_new_post_text() || :write_new_post.l(:category=>@category.name)
      %ul.list.checks
        %li
          %a{:href=>signup_url, :title=>:sign_up_for_a_.l+" #{configatron.community_name} "+:account.l}=:sign_up_for_an_account.l
          %br
            %small
              =:have_an_account.l
              %a{:href=>login_url, :title=>:log_in_to_your.l+" #{configatron.community_name} "+:account.l}
                &raquo;
                =:login.l

  -box :class => "alt" do 
    %h3=:top_writers.l
    - @active_users.each do |user|
      = render :partial => "users/sidebar_user", :locals => {:user => user} 
      
  -box :class => "alt" do 
    %h3=:popular_category.l(:name => @category.name)
    %ul.list.page    
      - @popular_posts.each do |post|
        =render :partial => 'posts/sidebar_post', :locals => {:post => post}


#yui-main
  .yui-b
    -box :class => "hfeed" do 
      %h3      
        =:show_category.l :category => @category.name
        %ul.subnav
          %li= link_to :recent.l, category_path(@category), {:class => (params[:popular] ? '' : 'active')}
          %li= link_to :popular.l, category_path(@category, :popular => 'DESC'), {:class => (params[:popular] ? 'active' : '')}  

      = render :partial => 'posts/post', :collection => @posts      
      - if @posts.total_count > 1
        = paginate @posts

app/views/friendships/_friendship.html.haml
- user = friendship.friend

.yui-gf.row
  .yui-u.first.centered= image_tag( user.avatar_photo_url(:thumb), :class => "polaroid" )
  .yui-g
    .yui-u.first
      %h2= link_to user.login, user_path(user)
      - if user.metro_area      
        = "#{:from.l} #{user.location}"
        %br 
      %p= friendship.friendship_status.name.l
      %p
        =:requested.l
        = time_ago_in_words friendship.created_at

    .yui-u= friendship_control_links(friendship) if @is_current_user

app/views/friendships/_friendships.html.erb
<table>
  <tr>
  </tr>
  
<% for friendship in @friendships %>
  <tr>
    <td><%= friendship.friend.login %>, <%= friendship.friendship_status.name %></td>
    <td><%= friendship.initiator? ? "initiator" : "not initiator" %></td>
    <td><%= time_ago_in_words friendship.created_at %></td>
    <td><%= link_to(:accept.l, accept_user_friendship_path(@user, friendship), :method => :put) unless friendship.initiator? %></td>
    <td><%= link_to(:deny.l, user_friendship_path(friendship.user, friendship), :confirm => :are_you_sure.l, :method => :delete) %></td>
  </tr>
<% end %>
</table>

app/views/friendships/accepted.html.haml
.yui-b= render :partial => 'users/profile_user_info_sidebar'

#yui-main
  .yui-b
    -box :id => "friends" do
      %h3
        =:accepted_friendships.l(:count => @friend_count)
        = link_to "(#{@pending_friendships_count} "+:pending.l+")", pending_user_friendships_path(@user) if  (@pending_friendships_count > 0)
      .pagination=paginating_links @friendships if @friendships.total_count > 1
      
      .clear
      .user_list= render :partial => "friendships/friendship", :collection => @friendships

app/views/friendships/denied.html.haml
.yui-b= render :partial => 'users/profile_user_info_sidebar'

#yui-main
  .yui-b
    -box :id => "friends" do
      %h3
        =:denied_friendships.l
      .user_list= render :partial => "friendships/friendship", :collection => @friendships

app/views/friendships/index.html.erb
<br>
<br>
<%= link_to "&raquo; #{:click_here_to_view_as_a_list.l}".html_safe, accepted_user_friendships_path(@user) %>

app/views/friendships/pending.html.haml
.yui-b= render :partial => 'users/profile_user_info_sidebar'

#yui-main
  .yui-b
    -box :id => "friends" do
      %h3= :pending_friendships.l
      .user_list= render :partial => "friendships/friendship", :collection => @friendships

app/views/friendships/show.html.haml
-box do
  %h3=:friendship_request_detail.l
  - if @friendship.initiator? && @friendship.pending?
    =:waiting_for.l 
    = @friendship.friend.login
    =:to_accept.l
  - elsif @friendship.pending?
    =:this_friendship_is_pending.l 
    = link_to :click_to_accept_it.l, accept_user_friendship_path(@user, @friendship), :method => :put

  %br
  = link_to :back.l, accepted_user_friendships_path(@user)

app/views/mocks/mock_activities.html.haml
%h1 Timeline

.row
  = 9.times do
    .large-4.small-6.columns
      .panel
        %img{src: "https://s3.amazonaws.com/uifaces/faces/twitter/chadengle/73.jpg"}
        %span just posted a product
        %img{src: "http://www.calessia.ro/wp-content/uploads/wpsc/product_images/thumbnails/colier_calessia_pietre_semipretioase.JPG"}/
        %h5 Colier pietre pretioase
        %h6.subheader $75.00
        %button.button.success.radius Buy

app/views/mocks/mock_products.html.haml
%h1 Mocks#mock_products
%p Find me in app/views/mocks/mock_products.html.haml

app/views/photo_manager/index.html.haml
.yui-b.sidebar
  -box do 
    %h3=:links.l
    %ul.checks
      %li=link_to :view_all_my_photos.l, user_photos_path(current_user)
      %li=link_to :new_photo.l, new_user_photo_path(current_user)
      %li=link_to :new_album.l, new_user_album_path(current_user)

#yui-main
  .yui-b
    -box do 
      %h3= :albums.l
      %table{:border => 0, :width => '100%'}
        %thead
          %tr
            %th=:title.l
            %th=:preview.l
            %th=:created_at.l
            %th=:actions.l
        %tbody
          - @albums.each do |album|
            %tr            
              %td= link_to album.title, user_album_path(current_user,album)
              %td
                - if album.photos[0] 
                  =link_to image_tag( album.photos[0].photo.url(:thumb), :size => "50x50"), user_photo_path(current_user, album.photos[0])
                - if album.photos[1] 
                  =link_to image_tag( album.photos[1].photo.url(:thumb), :size => "50x50"), user_photo_path(current_user, album.photos[1])
                - if album.photos[2] 
                  =link_to image_tag( album.photos[2].photo.url(:thumb), :size => "50x50"), user_photo_path(current_user, album.photos[2])
              %td
                %abbr{:title=>"#{album.created_at}"}= album.created_at.strftime("%Y/%m/%d")
              %td
                = link_to :edit.l, edit_user_album_path(current_user,album) 
                = " | "
                = link_to :add_photos.l, new_user_album_photo_path(current_user,album)
                = " | "
                = link_to :destroy.l, user_album_path(current_user,album), :confirm => :delete_album_and_photos.l, :method => :delete
      .pagination= paginating_links(@albums,{:name => "page_albums"}) if @albums.total_count > 1


      %h3= :not_assigned_photos.l
      #photos.yui-u.box
        - @photos_no_albums.each do |photo|
          = link_to image_tag( photo.photo.url(:thumb), :class => "polaroid"), user_photo_path(current_user, photo)
        .pagination= paginating_links @photos_no_albums if @photos_no_albums.total_count > 1

app/views/sb_posts/_dummy_forum_post.html.erb
<tr class="hentry">
  <td style="padding:5px; width:16px;" class="c1">
    <%= image_tag "clearbits/comment.gif", :class => "icon grey", :title => :no_recent_activity.l+" #{post}", :plugin => "community_engine" %>
  </td>
  <td class="c2">
    <%= link_to h(post.title), user_post_path(post.user, post), :class => "entry-title", :rel => "bookmark", :target => '_blank' %>
  </td>
  <td class="ca inv stat"><%= post.comments.count %></td>
  <td class="ca inv stat"><%= number_with_delimiter(post.view_count) %></td>
  <td class="lp">
    by <span class="author"><strong class="fn"><%= h(post.user.display_name) %></strong></span>
  </td>
</tr>

app/views/sb_posts/_edit.html.erb
<div id="edit" class="editbox">
<div class="container">
  <%= remote_form_for :post, @post, :url => sb_post_path(:forum_id => @post.forum_id, :topic_id => @post.topic_id, :id => @post), :html => { :method => :put, :class => "MainForm" }, :before => "$('editbox_spinner').show();tinyMCE.triggerSave();" do |f| -%>

  <table width="100%" border="0" cellpadding="0" cellspacing="0">
    <tr>
      <td rowspan="2" width="70%">
        <%= f.text_area :body, :rows => 10, :id => "edit_post_body", :class => "rich_text_editor" %>
      </td>
      <td style="vertical-align:top;">

        <p>
        	<%= ajax_spinner_for "editbox", "spinner_black.gif" %>	
					<%= submit_tag :save_changes.l %> <%= :or.l %>  <%= link_to_function(:cancel.l, "EditForm.cancel()") %>
	
	        <%= link_to(:delete_this_post.l, sb_post_path(:forum_id => @post.topic.forum, :topic_id => @post.topic, :id => @post, :page => params[:page]), :class => "utility", :method => :delete, :confirm => :are_you_sure_you_want_to_delete_this_post.l) %>  
	
				</p>

      </td>
    </tr>
    <tr>
      <td valign="bottom" style="vertical-align:bottom;padding-bottom:15px;">

      </td>
    </tr>
  </table>
  <% end -%>
</div>
</div>
<%= tiny_mce_init_if_needed %>

app/views/sb_posts/_reply_form.html.haml
= content_tag 'p', h(flash[:bad_reply]), :class => 'notice' if flash[:bad_reply]
.errors
= remote_form_for :post, @post, :url => sb_posts_path(:forum_id => @forum, :topic_id => @topic, :page => @topic.last_page), :html => {:class => "MainForm"}, :before => "$('editbox_spinner').show();tinyMCE.triggerSave()" do |f|
  %table{"cellspacing"=>"0", "border"=>"0", "cellpadding"=>"0", "width"=>"100%"}
    %tr
      %td{"rowspan"=>"2", "width"=>"60%"}
        = f.text_area :body, :style => "width: 99%; height: 300px;", :class => "rich_text_editor"
      - if !logged_in? && configatron.recaptcha_pub_key && configatron.recaptcha_priv_key 
        %td{"style"=>"vertical-align:top;"}
          %label{"for"=>"comment[author_name"}
            =:name.l
            %em="(#{:optional.l})"
          = f.text_field :author_name, :size => 35

          %label{"for"=>"comment[author_email"}
            ="#{:email.l}:"
            %em="(#{:comment_author_email_required.l})"
          = f.text_field :author_email, :size => 35        

          %label{"for"=>"comment[author_url"}
            =:comment_web_site_label.l
            %em="(#{:optional.l})"
          = f.text_field :author_url, :size => 35                  
        %td{"style"=>"vertical-align:top; text-align: center;padding-left: 20px;"}
          = recaptcha_tags :ajax => true
          %p
            = ajax_spinner_for "editbox", "spinner_black.gif"                    
            = submit_tag :save_reply.l
            =:or.l + " #{link_to_function :cancel.l, "$('reply').hide()"}"
      -else
        %td{"style"=>"vertical-align:top;"}
          %p
            = ajax_spinner_for "editbox", "spinner_black.gif"                    
            = submit_tag :save_reply.l
            ="#{:or.l} #{link_to_function :cancel.l, "$('reply').hide()"}".html_safe                  
    %tr
      %td{"style"=>"vertical-align: bottom; padding-bottom:15px;"}

app/views/sb_posts/_sb_post.html.haml
- unless post.eql?(@posts.to_a.first)
  %tr.spacer
    %td{"colspan"=>"2"}
      %a{"name"=>"#{post.dom_id}", "id"=>"#{post.dom_id}"} &nbsp;
    
%tr.post{"id"=>"posts-#{post.dom_id}-row"}
  %td.author.vcard{:width => "15%"}
    .date
      %a{"href"=>"##{post.dom_id}", "rel"=>"bookmark"}
        %abbr.updated{"title"=>"#{post.created_at.xmlschema}"}= time_ago_in_words(post.created_at)

    -if post.user
      = avatar_for post.user    
      %span.fn
        = link_to truncate(h(post.username), :length => 15), user_path(post.user), :class => (post.topic.editable_by?(post.user) ? "admin" : nil)
      %span.posts= pluralize post.user.sb_posts_count, :post.l
    -else
      = image_tag(configatron.photo.missing_thumb, :height => '32', :width => '32', :class => 'photo')        
      %span.fn
        =truncate(h(post.username), :length => 15)


    - if logged_in? && post.editable_by?(current_user)
      %p
        %span.edit
          = ajax_spinner_for "edit-post-#{post.id}", "spinner_bounce.gif"
          = link_to_remote(:edit_post.l, {:url => edit_forum_topic_sb_post_path(@forum, @topic, post), :method => :get, :before => "EditForm.init(#{post.id});", :condition => "!EditForm.isEditing(#{post.id})" }, {:class => "utility"})
        - if admin? && post.user && !post.user.admin?
          %div{"class"=>"make-moderator-#{post.user_id}"}
            = render :partial => '/moderators/toggle', :locals => {:user => post.user, :forum => @forum}

  %td.body.entry-content{"id"=>"post-body-#{post.id}", :width => '85%'}
    = link_to_function image_tag('clearbits/comment.gif', :class => 'icon reply'), "$('reply').toggle()" if logged_in?
    = raw post.body

app/views/sb_posts/edit.html.erb
<h1><%= :edit_post.l %></h1>

<h2><%= link_to h(@post.topic.title), forum_topic_path(@post.forum_id, @post.topic) %></h2>

<%= link_to(:delete_this_post.l, sb_post_path(:forum_id => @post.forum_id, :topic_id => @post.topic, :id => @post, :page => params[:page]), 
      :class => "utility", :method => :delete, :confirm => :are_you_sure_you_want_to_delete_this_post.l) %>

<%= error_messages_for :topic %>
<% form_for :post, :html => { :method => :put }, 
     :url  => sb_post_path(:forum_id => params[:forum_id], :id => params[:topic_id], :id => @post, :page => params[:page]) do |f| -%>
<%= f.text_area :body, :class => "rich_text_editor" %>
<%= submit_tag :save.l %> <%= :or.l %> <%= link_to :cancel.l, forum_topic_path(:forum_id => params[:forum_id], :id => params[:topic_id], :page => params[:page]) %>
<% end -%>

app/views/shared/_admin_nav.html.haml
-box do
  %h3=:admin.l

  %ul.list
    %li= link_to_unless_current :features.l, homepage_features_path
    %li= link_to_unless_current :categories.l, categories_path
    %li= link_to_unless_current :metro_areas.l, metro_areas_path
    %li= link_to_unless_current :events.l, admin_events_path
    %li= link_to_unless_current :statistics.l, statistics_path
    %li= link_to_unless_current :ads.l, ads_path 
    %li= link_to_unless_current :comments.l, admin_comments_path 
    %li= link_to_unless_current :tags.l, admin_tags_path
    %li= link_to_unless_current :admin_pages.l, admin_pages_path
    - if @admin_nav_links.any?
      - @admin_nav_links.each do |link|
        %li=link_to link[:name], link[:url]
    
    
    %li= link_to :cache_clear_link.l, admin_clear_cache_path, :confirm => :are_you_sure.l

app/views/shared/_bio_help.html.haml
- if @user.vendor?
  = :user_vendor_offer.l
- else
  = :user_bio_help.l

app/views/shared/_box.html.haml
.box{html_options}
  %div{:class => "#{html_options[:content_class]}"}
    =body

app/views/shared/_contact.html.haml
-box :class => "alt" do 
  %h3=:need_to_contact_us.l
  %p
    =:dont_wait_its.l
    %a{:href=>"mailto:#{configatron.support_email}"}= configatron.support_email

app/views/shared/_footer_content.html.haml
.large-12.columns
  -box :class => "fresh" do 
    %h3=:whats_fresh.l
    - @recent_activity.each do |activity|
      - if activity.item_type == "Photo"
        =render :partial => "activities/activity", :locals => {:activity => activity }
    %h6.all= link_to :see_all_activity.l, activities_path

app/views/shared/_header.html.haml
.row
  .large-12.columns
    - if logged_in?
      = render :partial => 'shared/user_menu'
      - if current_user.unread_messages?
        %span#newmail
          = link_to :unread_messages.l(:count => current_user.unread_message_count), user_messages_path(current_user)
    - else
      %span.right
        =:welcome_message.l(:login_link => link_to(:log_in.l, login_path), :signup_link => link_to(:sign_up.l, signup_path))

.row.logo-header
  .large-2.small-2.small-centered.columns
    %h1
      %a{:href=>home_url, :title=>"#{configatron.community_name}"}= image_tag("logo.png")

%nav.top-bar{"data-topbar" => ""}
  %section.top-bar-section
    / Right Nav Section
    %ul.right
      %li
        %a{href: "#"} Account Balance: $25.00
      %li.has-form
        .row.collapse
          .large-8.small-9.columns
            %form{:method=>"get", :action=>"http://www.google.com/custom", :target=>"_top"}
              %input{placeholder: "Find Stuff", type: "text", name: "q"}
              %input{ :type=>"hidden", :name=>"domains", :value=>"#{home_url}"}
              %label{ :for=>"search",  :style=>"display: none"}
                = :search.l+" #{configatron.community_name}"
              %input{ :type=>"hidden", :name=>"sitesearch", :value=>"#{home_url}", :id=>"ss1"}
              %input{ :type=>"hidden", :name=>"client", :value=>"pub-9113954708528841"}
              %input{ :type=>"hidden", :name=>"forid", :value=>"1"}
              %input{ :type=>"hidden", :name=>"channel", :value=>"1842224655"}
              %input{ :type=>"hidden", :name=>"ie", :value=>"ISO-8859-1"}
              %input{ :type=>"hidden", :name=>"oe", :value=>"ISO-8859-1"}
              %input{ :type=>"hidden", :name=>"cof", :value=>"GALT:#008000;GL:1;DIV:#FFFFFF;VLC:663399;AH:center;BGC:FFFFFF;LBGC:FFFFFF;ALC:0066CC;LC:0066CC;T:000000;GFNT:0000FF;GIMP:0000FF;LH:50;LW:90;S:http://#{home_url};FORID:1"}
              %input{ :type=>"hidden", :name=>"hl", :value=>"en"}

          .large-4.small-3.columns
            %a.button.expand{href: "#"} Search

    / Left Nav Section
    %ul.left
      %li
        -#%a{href: "#{activities_path}"} Timeline
        %a{href: "#{mock_activities_path}"} Timeline
      %li
        %a{href: "#{users_path}"} Users
      %li
        %a{href: "#{popular_path}"} Popular
      - if current_user
        %li
          %a{href: "#{user_path(current_user)}"} My Profile